name = "tgbotcredit"
main = "index.js"
compatibility_date = "2026-04-15"

# Fill this with a real KV namespace id from your Cloudflare account.
[[kv_namespaces]]
binding = "DB"
id = "d6f69b40-6768-431d-a2a4-2233aa802bc7"
